config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # get "/contact", to: "pages#contact"
  get "/about", to: "pages#about"
  get "/dashboard", to: "pages#dashboard"
  get "/contact", to: "pages#contact"
  get "/books", to: "pages#books"

  resources :illustrations, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/illustration.rb
class Illustration < ApplicationRecord
  has_one_attached :main_photo
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_illustration, except: [:new, :create, :index]
  before_action :check_device

  def index
    @illustrations = policy_scope(Illustration).order("id DESC")
    @language = params[:language] || "en"
  end

  def show
    authorize @illustration
  end

  def new
    @language = params[:language] || "en"
    @illustration = Illustration.new
    authorize @illustration
  end

  def create
    @language = params[:language] || "en"
    @illustration = Illustration.new(illustration_params)
    authorize @illustration
    if @illustration.save
      redirect_to illustrations_path(language: @language)
    else
      render :new
    end
  end

  def edit
    authorize @illustration
  end

  def update
    authorize @illustration
  end

  def destroy
    authorize @illustration
  end

  private

  def set_illustration
    @illustration = Illustration.find(params[:id])
  end

  def illustration_params
    params.require(:illustration).permit(:description, :main_photo, photos: [])
  end

  private

  def check_device
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :contact, :books]
  before_action :check_device

  def home
    @language = params[:language] || "en"
  end

  def dashboard
    @language = params[:language] || "en"
  end

  def about
    @language = params[:language] || "en"
  end

  def contact
    @language = params[:language] || "en"
  end

  def books
    @language = params[:language] || "en"
  end

  private

  def check_device
    request.variant = :phone if browser.device.mobile?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/illustrations/edit.html.erb
hello

app/views/illustrations/new.html.erb
<%= simple_form_for @illustration do |f| %>
  <%= f.input :description %>
  <%= f.input :main_photo, as: :file %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Camila Modena • Illustration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="title" content="Camila Modena" />
    <meta name="description" content="Illustrations, designs and digital artwork">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/x-icon" href="<%= image_path "favicon.ico" %>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless browser.device.mobile? %>
      <%= render "shared/languages" %>
    <% end %>

    <% if browser.device.mobile? %>
      <div class="layout-mobile">
        <% unless current_page?(root_path) || current_page?(new_user_session_path) %>
          <%= render "shared/navbar_mobile" %>
        <% end %>
        <%= yield %>
      </div>
    <% end %>

    <% unless current_page?(root_path) || current_page?(new_user_session_path) || browser.device.mobile? %>
      <div class="layout">
        <%= render "shared/navbar" %>
        <div style="width: 100%;">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <% unless browser.device.mobile? %>
        <%= yield %>
      <% end %>
    <% end %>

    <% if current_page?(about_path) %>
      <%= image_tag "about/footer.png", class: "#{ browser.device.mobile? ? "about-footer-mobile" :  "about-footer" }" %>
    <% elsif current_page?(books_path) %>
      <div class="<%= browser.device.mobile? ? "fish-footer-mobile" :  "fish-footer" %>">
        <%= image_tag "books/the_fish_in_the_sea/fish.png" %>
      </div>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-top">
  <%= image_tag "about/about_photo.png", class: "about-photo" %>

  <% if @language == "en" %>
    <div class="about-text">
      <div>
        <%= image_tag "about/about_en.png", class: "about-title" %>
      </div>
      <p>
        I'm an illustrator and web development teacher. I'm Brazilian but grew up in England. My identity crisis as the English cousin in Brazil but the Brazilian friend in England eventually took me to live in Spain, where I'm just another person 'not from here'.
      </p>

      <br>

      <p>
        I've been drawing my entire life but only realised after being approached to illustrate a <%= link_to "children's book", books_path(language: @language) %> for the charity Learn Achieve Become that art could have a purpose. Soon after, I learned to code and decided to see how I could combine these two things.
      </p>
    </div>
  <% end %>

  <% if @language == "pt" %>
    <div class="about-text">
      <div>
        <%= image_tag "about/about_pt.png", class: "about-title", id: "pt" %>
      </div>
      <p>
        Sou ilustradora e professora de programação. Sou brasileira mas cresci na Inglaterra. Minha crise de identidade como a prima inglesa no Brasil mas a amiga brasileira na Inglaterra acabou me levando a morar aqui na Espanha, onde sou apenas mais uma pessoa 'não daqui'.
      </p>

      <br>

      <p>
        Desenho desde criança, mas só percebi que a arte poderia ter um propósito depois de ser abordada para ilustrar um <%= link_to "livro infantil", books_path(language: @language) %> para a ONG Learn Achieve Become. Logo depois, aprendi a programar e decidi ver como poderia combinar as duas coisas.
      </p>
    </div>
  <% end %>

  <% if @language == "es" %>
    <div class="about-text">
      <div>
        <%= image_tag "about/about_es.png", class: "about-title" %>
      </div>
      <p>
        Soy ilustradora y professora de programación. Soy brasileña pero crecí en Inglaterra. Mi crise de identidad como la prima inglesa en Brasil pero la amiga brasileña en Inglaterra me acabó llevandome a vivir aquí en españa, donde soy simplemente una persona más 'no de aquí'.
      </p>

      <br>

      <p>
        Dibujo desde niña, pero sólo me di cuenta de que el arte podía tener un propósito cuande me propusieron ilustrar un <%= link_to "libro infantil", books_path(language: @language) %> para la ONG Learn Achieve Become. Poco después, aprendí a programar y me puse a explorar como poría mezclar ambas cosas.
      </p>
    </div>
  <% end %>
</div>

<div class="about-bottom">
  <% if @language == "en" %>
    <p>
      Aside from drawing and coding, I spend most of my time listening to cumbia or podcasts about the GDR, imagining what my dog's accent would be like if he could talk, and saving videos of other people making recipes on the internet, despite knowing full well I'll never make them.
    </p>

    <br>

    <p>
      For all types of work, including websites, illustrations, comics or books, animations and tattoo designs, get in touch using the links <span class="contact-desktop">to the left</span><span class="contact-tablet">on the <%= link_to "contact page", contact_path(language: @language)%></span> :)
    </p>
  <% end %>

  <% if @language == "es" %>
    <p>
      Aparte de dibujar y programar, paso la mayor parte de mi tiempo escuchando cumbia o podcasts sobre alemania oriental, imaginando cómo sería el acento de mi perro si pudiera hablar y guardando vídeos de otras personas cocinando recetas en online sabiendo muy bien que nunca las haré.
    </p>

    <br>

    <p>
      Para cualquier tipo de trabajo, incluyendo webs, ilustraciones, comics o libros, animaciónes y diseños de tatuajes, ponte en contacto conmigo a través de los links <span class="contact-desktop">a la izquierda</span><span class="contact-tablet">en la <%= link_to "página de contacto", contact_path(language: @language)%></span> :)
    </p>
  <% end %>

  <% if @language == "pt" %>
    <p>
      Além de desenhar e programar, passo a maioria do meu tempo ouvindou cumbia ou podcasts sobre a Alemanha Oriental, imaginando como seria o sotaque do meu cachorro se ele pudesse falar, e salvando vídeos de outras pessas fazendo receitas que eu também quero fazer, mas sabendo que nunca as farei.
    </p>

    <br>

    <p>
      Para qualquer tipo de trabalho, including sites, ilustrações, histórias em quadrinhos ou livros, animações e desenhos de tatuagem, entre em contato através dos links <span class="contact-desktop">no lado esquerdo</span><span class="contact-tablet">na <%= link_to "página de contato", contact_path(language: @language)%></span> :)
    </p>
  <% end %>
</div>

<%= render "shared/navbar_tablet" %>

app/views/pages/admin.html.erb
<%= link_to "Add illustration", new_illustration_path %>

app/views/pages/contact.html+phone.erb
<%= link_to :back do %>
  <%= image_tag "illustrations/arrow_col.png", class: "back-mobile"%>
<% end %>

<div class="container-mobile contact-mobile">
  <div class="contact-header">
    <%= image_tag "icons/star.png", class: "footer-star" %>
    <%= image_tag "menu_#{@language}/contact_#{@language}_bw.png", class: "menu-item-mobile" %>
    <%= image_tag "icons/star.png", class: "footer-star" %>
  </div>

  <%= mail_to "cmodena95@gmail.com" do %>
    <%= image_tag "contact/email.png", class: "contact-email" %>
  <% end %>

  <%= link_to "https://www.instagram.com/camillustrate", target: "_blank" do %>
    <%= image_tag "contact/instagram.png", class: "contact-instagram" %>
  <% end %>
</div>

app/views/pages/dashboard.html+phone.erb
<%= link_to "Add illustration", new_illustration_path %>

app/views/pages/dashboard.html.erb
<%= link_to "Add illustration", new_illustration_path %>

app/views/pages/home.html+phone.erb
<div data-controller="parallax-mobile">
  <div class="banner-container">
    <div class="header-container-mobile">
      <%= image_tag "header.png", class: "header-mobile", data: {parallax_mobile_target: "header"} %>
    </div>

    <div class="banner-mobile" data-action="scroll@window->parallax-mobile#move">
      <%= image_tag "https://res.cloudinary.com/cmodena95/image/upload/v1707330374/mountain_b2dn8j.png", class: "mountain-mobile", data: {parallax_mobile_target: "mountain"} %>
      <div class="banner-bg-mobile">
        <%= image_tag "https://res.cloudinary.com/cmodena95/image/upload/v1707330557/tree_j0olnd.png", class: "tree-mobile", data: {parallax_mobile_target: "tree"} %>
        <%= image_tag "https://res.cloudinary.com/cmodena95/image/upload/v1707330653/houses_bce5od.png", class: "houses-mobile", data: {parallax_mobile_target: "houses"} %>

        <%= image_tag "sun.png", class: "sun-mobile", data: {parallax_mobile_target: "sun"} %>
      </div>
    </div>
  </div>

  <div class="home-mobile" data-controller="rotate">

    <div class="home-menu-mobile" data-controller="hover" data-action="scroll@window->rotate#transform">

      <div class="home-menu-level-1-mobile">
        <%= image_tag "home_objects/pizza.png", class: "pizza-mobile", data: { rotate_target: "pizza" }%>
        <%= image_tag "home_objects/swan.png", class: "swan-mobile", data: { rotate_target: "swan" }%>
      </div>

      <%= link_to illustrations_path(language: @language) do %>
        <%= image_tag "menu_#{@language}/illustrations_#{@language}_bw.png", class: "menu-item-mobile", data: {
          action: "mouseover->hover#color mouseout->hover#decolor",
          color: "#{image_path "menu_#{@language}/illustrations_#{@language}_col.png"}",
          bw: "#{image_path "menu_#{@language}/illustrations_#{@language}_bw.png"}"} %>
      <% end %>

      <div class="home-menu-level-2-mobile">
        <%= image_tag "home_objects/guava.png", class: "guava-mobile", data: { rotate_target: "guava" } %>

        <div class="flex-column" style="gap: 1rem;">
          <%= link_to about_path(language: @language) do %>
            <%= image_tag "menu_#{@language}/about_#{@language}_bw.png", class: "menu-item-mobile-sm", data: {action: "mouseover->hover#color mouseout->hover#decolor",
            color: "#{image_path "menu_#{@language}/about_#{@language}_col.png"}",
            bw: "#{image_path "menu_#{@language}/about_#{@language}_bw.png"}"} %>
          <% end %>

          <%= link_to books_path(language: @language) do %>
            <%= image_tag "menu_#{@language}/books_#{@language}_bw.png", class: "menu-item-mobile-sm", data: {action: "mouseover->hover#color mouseout->hover#decolor",
            color: "#{image_path "menu_#{@language}/books_#{@language}_col.png"}",
            bw: "#{image_path "menu_#{@language}/books_#{@language}_bw.png"}"} %>
          <% end %>
        </div>

        <%= image_tag "home_objects/statue.png", class: "statue-mobile", data: { rotate_target: "statue" }%>
      </div>

      <%= link_to contact_path(language: @language) do %>
        <%= image_tag "menu_#{@language}/contact_#{@language}_bw.png", class: "menu-item-mobile-sm", data: {action: "mouseover->hover#color mouseout->hover#decolor",
        color: "#{image_path "menu_#{@language}/contact_#{@language}_col.png"}", 
        bw: "#{image_path "menu_#{@language}/contact_#{@language}_bw.png"}"} %>
      <% end %>

      <%= image_tag "home_objects/sushi.png", class: "sushi-mobile", data: { rotate_target: "sushi" }%>

    </div>

  </div>
</div>


<%# footer %>
<div class="footer-mobile" data-controller="hover">
  <div class="footer-icons">
    <%= image_tag "icons/star.png", class: "footer-star-mobile" %>

    <%= link_to "https://www.instagram.com/camillustrate", target: "_blank" do %>
      <%= image_tag "icons/instagram_bw.png", class: "footer-icon-mobile", data: {action: "mouseover->hover#color mouseout->hover#decolor",
      color: "#{image_path "icons/instagram_col.png"}", 
      bw: "#{image_path "icons/instagram_bw.png"}"} %>
    <% end %>

    <%= image_tag "icons/star.png", class: "footer-star" %>

    <%= mail_to "cmodena95@gmail.com" do %>
      <%= image_tag "icons/email_bw.png", class: "footer-icon-mobile", data: {action: "mouseover->hover#color mouseout->hover#decolor",
      color: "#{image_path "icons/email_col.png"}", 
      bw: "#{image_path "icons/email_bw.png"}"} %>
    <% end %>

    <%= image_tag "icons/star.png", class: "footer-star" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-home" data-controller="hover">
  <%= link_to root_path(language: @language) do %>
    <%= image_tag "logo.png", class: "logo",
      data: {action: "mouseover->hover#color mouseout->hover#decolor",
      color: "#{image_path "logo_animated_en.png"}", 
      bw: "#{image_path "logo.png"}"}  %>
  <% end %>

  <div class="navbar-menu">
    <div class="navbar-menu-items">
      <%= link_to illustrations_path(language: @language) do %>
        <%= image_tag "menu_#{@language}/illustrations_#{@language}_#{current_page?(illustrations_path) ? "col" : "bw"}.png", class: "navbar-item navbar-illustration", id: "#{current_page?(illustrations_path) ? "disable-hover" : ""}",
          data: {action: "#{current_page?(illustrations_path) ? "" : "mouseover->hover#color mouseout->hover#decolor"}",
          color: "#{image_path "menu_#{@language}/illustrations_#{@language}_col.png"}", 
          bw: "#{image_path "menu_#{@language}/illustrations_#{@language}_bw.png"}"} %>
      <% end %>

      <%= link_to about_path(language: @language) do %>
        <%= image_tag "menu_#{@language}/about_#{@language}_#{current_page?(about_path) ? "col" : "bw"}.png", class: "navbar-item", id: "#{current_page?(about_path) ? "disable-hover" : ""}",
            data: {action: "#{current_page?(about_path) ? "" : "mouseover->hover#color mouseout->hover#decolor"}",
            color: "#{image_path "menu_#{@language}/about_#{@language}_col.png"}", 
            bw: "#{image_path "menu_#{@language}/about_#{@language}_bw.png"}"} %>
      <% end %>

      <%= link_to books_path(language: @language) do %>
        <%= image_tag "menu_#{@language}/books_#{@language}_#{current_page?(books_path) ? "col" : "bw"}.png", class: "navbar-item", id: "#{current_page?(books_path) ? "disable-hover" : ""}",
            data: {action: "#{current_page?(books_path) ? "" : "mouseover->hover#color mouseout->hover#decolor"}",
            color: "#{image_path "menu_#{@language}/books_#{@language}_col.png"}", 
            bw: "#{image_path "menu_#{@language}/books_#{@language}_bw.png"}"} %>
      <% end %>

    </div>
      
    <div class="navbar-icons">
      <%= image_tag "icons/star.png", class: "navbar-star" %>

      <%= link_to "https://www.instagram.com/camillustrate", target: "_blank" do %>
        <%= image_tag "icons/instagram_bw.png", class: "navbar-icon", data: {action: "mouseover->hover#color mouseout->hover#decolor",
        color: "#{image_path "icons/instagram_col.png"}", 
        bw: "#{image_path "icons/instagram_bw.png"}"} %>
      <% end %>

      <%= image_tag "icons/star.png", class: "navbar-star" %>

      <%= mail_to "cmodena95@gmail.com" do %>
        <%= image_tag "icons/email_bw.png", class: "navbar-icon", data: {action: "mouseover->hover#color mouseout->hover#decolor",
        color: "#{image_path "icons/email_col.png"}", 
        bw: "#{image_path "icons/email_bw.png"}"} %>
      <% end %>

      <%= image_tag "icons/star.png", class: "navbar-star" %>
    </div>
  </div>
</div>

app/views/shared/_navbar_mobile.html.erb
<div data-controller="menu">
  <div class="menu-mobile menu-hidden" data-menu-target="menu">
    <div class="menu-mobile-options">
      <%= link_to root_path(language: @language) do %>
        <%= image_tag "logo.png", class: "logo-mobile",
          data: {action: "mouseover->hover#color mouseout->hover#decolor",
          color: "#{image_path "logo_animated_en.png"}", 
          bw: "#{image_path "logo.png"}"}  %>
      <% end %>

      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to illustrations_path(language: @language), data: {languages_target: "illustrationsLink"} do %>
          <%= image_tag "menu_#{@language}/illustrations_#{@language}_#{current_page?(illustrations_path) ? "col" : "bw"}.png", class: "menu-item-mobile", data: {
          languages_target: "illustrations",
          en: "#{image_path "menu_en/illustrations_en_bw.png"}",
          es: "#{image_path "menu_es/illustrations_es_bw.png"}",
          pt: "#{image_path "menu_pt/illustrations_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>

      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to books_path(language: @language), data: {languages_target: "booksLink"} do %>
          <%= image_tag "menu_#{@language}/books_#{@language}_#{current_page?(books_path) ? "col" : "bw"}.png", class: "menu-item-mobile-sm books-mobile", data: {
          languages_target: "books",
          en: "#{image_path "menu_en/books_en_bw.png"}",
          es: "#{image_path "menu_es/books_es_bw.png"}",
          pt: "#{image_path "menu_pt/books_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>
      
      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to about_path(language: @language), data: {languages_target: "aboutLink"} do %>
          <%= image_tag "menu_#{@language}/about_#{@language}_#{current_page?(about_path) ? "col" : "bw"}.png", class: "menu-item-mobile-sm", data: 
          {languages_target: "about",
          en: "#{image_path "menu_en/about_en_bw.png"}",
          es: "#{image_path "menu_es/about_es_bw.png"}",
          pt: "#{image_path "menu_pt/about_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>

      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to contact_path(language: @language), data: {languages_target: "contactLink"} do %>
          <%= image_tag "menu_#{@language}/contact_#{@language}_#{current_page?(contact_path) ? "col" : "bw"}.png", class: "menu-item-mobile", data: 
          {languages_target: "contact",
          en: "#{image_path "menu_en/contact_en_bw.png"}",
          es: "#{image_path "menu_es/contact_es_bw.png"}",
          pt: "#{image_path "menu_pt/contact_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>

      <%# LANGUAGES %>
      <div class="languages-mobile">
       <%= link_to request.params.merge(language: "en") do %>
        <%= image_tag "languages/en#{@language == "en" ? "_col": ""}.png", class: "language-icon-mobile" %>
      <% end %>
        
       <%= link_to request.params.merge(language: "es") do %>
        <%= image_tag "languages/es#{@language == "es" ? "_col": ""}.png", class: "language-icon-mobile", id: "es" %>
      <% end %>

       <%= link_to request.params.merge(language: "pt") do %>
        <%= image_tag "languages/pt#{@language == "pt" ? "_col": ""}.png", class: "language-icon-mobile", id: "pt" %>
      <% end %>
      </div>
    </div>
  </div>

  <%# <div class="menu-close-mobile" data-action="click->menu#toggleMenu" data-status="closed"> %>
    <%# <p>menu</p>
    <br>
    <p>X</p> %>
    <%= image_tag "menu.png", class: "menu-btn", data: {action: "click->menu#toggleMenu" } %>
  <%# </div> %>
</div>

app/views/shared/_navbar_tablet.html.erb
<div data-controller="menu" style="position: fixed; top: 0;">
  <div class="menu-mobile menu-hidden" data-menu-target="menu">
    <div class="menu-mobile-options">
      <%= link_to root_path(language: @language) do %>
        <%= image_tag "logo.png", class: "logo-mobile",
          data: {action: "mouseover->hover#color mouseout->hover#decolor",
          color: "#{image_path "logo_animated_en.png"}", 
          bw: "#{image_path "logo.png"}"}  %>
      <% end %>

      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to illustrations_path(language: @language), data: {languages_target: "illustrationsLink"} do %>
          <%= image_tag "menu_#{@language}/illustrations_#{@language}_#{current_page?(illustrations_path) ? "col" : "bw"}.png", class: "menu-item-tablet-illustrations", data: {
          languages_target: "illustrations",
          en: "#{image_path "menu_en/illustrations_en_bw.png"}",
          es: "#{image_path "menu_es/illustrations_es_bw.png"}",
          pt: "#{image_path "menu_pt/illustrations_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>

      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to books_path(language: @language), data: {languages_target: "booksLink"} do %>
          <%= image_tag "menu_#{@language}/books_#{@language}_#{current_page?(books_path) ? "col" : "bw"}.png", class: "menu-item-mobile-sm books-mobile", data: {
          languages_target: "books",
          en: "#{image_path "menu_en/books_en_bw.png"}",
          es: "#{image_path "menu_es/books_es_bw.png"}",
          pt: "#{image_path "menu_pt/books_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>
      
      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to about_path(language: @language), data: {languages_target: "aboutLink"} do %>
          <%= image_tag "menu_#{@language}/about_#{@language}_#{current_page?(about_path) ? "col" : "bw"}.png", class: "menu-item-mobile-sm", data: 
          {languages_target: "about",
          en: "#{image_path "menu_en/about_en_bw.png"}",
          es: "#{image_path "menu_es/about_es_bw.png"}",
          pt: "#{image_path "menu_pt/about_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>

      <div style="display: flex; align-items: center;">
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
        <%= link_to contact_path(language: @language), data: {languages_target: "contactLink"} do %>
          <%= image_tag "menu_#{@language}/contact_#{@language}_#{current_page?(contact_path) ? "col" : "bw"}.png", class: "menu-item-mobile", data: 
          {languages_target: "contact",
          en: "#{image_path "menu_en/contact_en_bw.png"}",
          es: "#{image_path "menu_es/contact_es_bw.png"}",
          pt: "#{image_path "menu_pt/contact_pt_bw.png"}"
          } %>
        <% end %>
        <%= image_tag "icons/star.png", class: "menu-star-mobile" %>
      </div>

      <%# LANGUAGES %>
      <div class="languages-mobile">
       <%= link_to request.params.merge(language: "en") do %>
        <%= image_tag "languages/en#{@language == "en" ? "_col": ""}.png", class: "language-icons-tablet" %>
      <% end %>
        
       <%= link_to request.params.merge(language: "es") do %>
        <%= image_tag "languages/es#{@language == "es" ? "_col": ""}.png", class: "language-icons-tablet", id: "es" %>
      <% end %>

       <%= link_to request.params.merge(language: "pt") do %>
        <%= image_tag "languages/pt#{@language == "pt" ? "_col": ""}.png", class: "language-icons-tablet", id: "pt" %>
      <% end %>
      </div>
    </div>
  </div>

  <%= image_tag "menu.png", class: "menu-btn", data: {action: "click->menu#toggleMenu" } %>
</div>